name: Playwright on Namespace Runners, with APT caching
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: namespace-profile-ns-integration-playwright
    steps:
      - uses: namespacelabs/nscloud-checkout-action@v7

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "" # Use Namespace caching instead

      - name: Set up Cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ~/.npm
            ~/.cache/ms-playwright
            /var/cache/apt

        # By default, apt cleans its caches after every `apt install`
      - name: Stop apt cleaning cache
        run: sudo rm /etc/apt/apt.conf.d/docker-clean

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: namespace-actions/upload-artifact@v1
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
