name: run-all.yml
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Once a day

jobs:
  github-runners:
    uses: ./.github/workflows/00-github-runners.yml
  namespace-cache:
    uses: ./.github/workflows/01-namespace-cache.yml
  namespace-apt-cache:
    uses: ./.github/workflows/02-namespace-apt-cache.yml
  namespace-docker:
    uses: ./.github/workflows/03-namespace-docker.yml